"""empty message

Revision ID: 178cbc062ee9
Revises: 0572e93518ce
Create Date: 2025-04-26 00:33:31.278715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178cbc062ee9'
down_revision = '0572e93518ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showTitle', sa.String(length=50), nullable=True),
    sa.Column('favoriteId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favoriteId'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    op.drop_table('favorites')
    # ### end Alembic commands ###
