"""empty message

Revision ID: 63337612cf39
Revises: 0763d677d453
Create Date: 2025-04-25 23:50:27.599861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63337612cf39'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
